### ISSUE TITLE
Misplaced tab mwe_en.tsv line 9834

### ISSUE THREAD

**Issue by eritain** [UCREL/Multilingual-USAS#14]
`in_ADP the_DET  altogether B5-` has tab between `the_DET` and `altogether`, space between `altogether` and `B5-` --- should be space first, tab second

**Comment by perayson** [comment]
Thanks also for flagging this. There's a missing POS tag on altogether. I'll check the original files.

**Comment by perayson** [comment]
Thanks again for noting this issue. @dml2611 and I have carried out extensive format checking for the English lexicons, and we've updated them here (https://github.com/UCREL/Multilingual-USAS/pull/21) and released them in the pymusas-models repo as version 0.3.3 (https://github.com/UCREL/pymusas-models/releases).
