### ISSUE TITLE
Auto Generating the Lexicon Statistics table in the README

### ISSUE THREAD

**Issue by apmoore1** [UCREL/Multilingual-USAS#7]
It is slightly tricky to auto generate the lexicon statistics table in the README as markdown does not allow embedding data from other files, apart from images, into a markdown file. Therefore, even though it is easy to create another file called `lexcion_statistics.md` with the statistics data generated through GitHub actions, e.g.:

```bash
python lexicon_statistics.py > lexicon_statistics.md
```

Getting the data from `lexicon_statistics.md` into `README.md` is difficult. At the moment the only solution is to do this manually by running `python lexicon_statistics.py` and copying the output into the README.

**Comment by perayson** [comment]
It would be fine to leave the stats as a separate markdown file I think ...

**Comment by apmoore1** [comment]
> It would be fine to leave the stats as a separate markdown file I think ...

This is now fixed with the #1 pull request, the lexicon statistics are in a separate file called [lexicon_statistics.md](https://github.com/UCREL/Multilingual-USAS/blob/master/lexicon_statistics.md), and the [CI GitHub action](https://github.com/UCREL/Multilingual-USAS/blob/master/.github/workflows/ci.yml#L42) auto generates this lexicon statistics file each time someone pushes to the repository.
